export { default as DoctorPage } from './components/DoctorPage'
export { default as DoctorAuth } from './components/DoctorAuth'
export { default as DoctorDashboard } from './components/DoctorDashboard'
export { default as DoctorProfile } from './components/DoctorProfile'
export { default as AvailabilityManager } from './components/AvailabilityManager'
export { useDoctorStore } from './store/doctorStore'
export type { Doctor, TimeSlot, Booking, DoctorState } from './types'
